### ISSUE TITLE
Typo in run args causes byzantine error

### ISSUE THREAD

**Issue by eschrock** [titan-data/titan#24]
## Expected Behavior

Accidentally forgot a "-" in "--name". Expected a nice error message from docker.

## Actual Behavior

```
$ titan run -- -d -name myrepo2 postgres:latest
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:287)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at kotlin.random.Random.<clinit>(Random.kt:242)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
	at java.lang.Class.ensureInitialized(DynamicHub.java:437)
	at io.titandata.titan.clients.Docker$Companion.fetchName(Docker.kt:168)
	at io.titandata.titan.providers.local.Run.run(Run.kt:24)
	at io.titandata.titan.providers.local.Run.run$default(Run.kt:20)
	at io.titandata.titan.providers.Local.run(Local.kt:122)
	at io.titandata.titan.commands.Run.run(Run.kt:25)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:112)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:19)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:166)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:164)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:181)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:200)
	at io.titandata.titan.Cli.main(Cli.kt:56)
Caused by: java.lang.InstantiationException: Type `kotlin.internal.jdk7.JDK7PlatformImplementations` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:740)
	at kotlin.internal.PlatformImplementationsKt.<clinit>(PlatformImplementations.kt:40)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
	... 17 more
```

## Steps to Reproduce the Problem

`titan run -- -d -name myrepo2 postgres:latest`

## Version

0.3.0

**Comment by mcred** [comment]
After #27, the output is:
```
Creating repository sudden_factor
Creating docker volume sudden_factor/v0 with path /var/lib/postgresql/data
Command failed: docker run --label io.titandata.titan --mount type=volume,src=sudden_factor/v0,dst=/var/lib/postgresql/data,volume-driver=titan --name sudden_factor -d -name myrepo2 postgres@sha256:9ee979b15082e0bd9526fde1717ffea0059e3bad936d5be9e9e5f3404f5d9375 
unknown shorthand flag: 'n' in -name
See 'docker run --help'.
```
Does this improve the output enough?

**Comment by eschrock** [comment]
Yes.
