### ISSUE TITLE
nil pointer exception

### ISSUE THREAD

**Issue by sourceful-karlson** [titan-data/titan#277]
## Expected Behavior

Describe what should have happened.
titan clone -n hello-world s3web://demo.titan-data.io/hello-world/postgres

and run postgres

## Actual Behavior

Describe what actually happened.

titan clone -n hello-world s3web://demo.titan-data.io/hello-world/postgres
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x165c694]

goroutine 1 [running]:
titan/internal/app/providers/common.Clone(0x7ffca58e8791, 0x2f, 0x7ffca58e8785, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002e5f00, ...)
        /Users/mcred/projects/titan/titan/internal/app/providers/common/Clone.go:52 +0x3f4
titan/internal/app/providers.local.Clone(...)
        /Users/mcred/projects/titan/titan/internal/app/providers/Local.go:45
titan/internal/app/commands.glob..func3(0x27194e0, 0xc0002e5ef0, 0x1, 0x3)
        /Users/mcred/projects/titan/titan/internal/app/commands/clone.go:33 +0x15e
github.com/spf13/cobra.(*Command).execute(0x27194e0, 0xc0002e5e90, 0x3, 0x3, 0x27194e0, 0xc0002e5e90)
        /Users/mcred/projects/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2719f60, 0x27331a0, 0x0, 0xc000084778)
        /Users/mcred/projects/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mcred/projects/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
titan/internal/app/commands.Execute()
        /Users/mcred/projects/titan/titan/internal/app/commands/root.go:54 +0x31
main.main()
        /Users/mcred/projects/titan/titan/cmd/titan/titan.go:23 +0x25

## Steps to Reproduce the Problem

Describe in as much detail as possible how to reproduce the problem.

titan install
titan clone -n hello-world s3web://demo.titan-data.io/hello-world/postgres

in a linux gitpod machine

## Version

Indicate the relevant versions of components. This may include the Titan
package version, operating system version, or other components relevant to
the project.

## Additional Information

Add any additional logs or debugging information if appropriate.

**Comment by mcred** [comment]
Is there any output from `titan ls`? What do the contents of `~/.titan/config` look like?

**Comment by mcred** [comment]
@sourceful-karlson do you still have this issue?

**Comment by sourceful-karlson** [comment]
apoogy, i will look this again over the weekend
