### ISSUE TITLE
Locally built images don't work

### ISSUE THREAD

**Issue by eschrock** [titan-data/titan#3]
## Expected Behavior

We should be able to use locally built images, but at the moment we require that a digest exist, which is only true for published images. We should remember both the name of the image and optionally the hash, preferring the latter but falling back to the former.

## Actual Behavior

```
$ titan run -- --name hello-world -p 8000:8000 -d dynamodb-local:latest
Creating repository hello-world
Creating docker volume hello-world/v0 with path /home/dynamodblocal/data
Exception in thread "main" org.json.JSONException: JSONArray[0] not found.
	at org.json.JSONArray.get(JSONArray.java:218)
	at io.titandata.titan.providers.local.Run.run(Run.kt:63)
	at io.titandata.titan.providers.local.Run.run$default(Run.kt:20)
	at io.titandata.titan.providers.Local.run(Local.kt:122)
	at io.titandata.titan.commands.Run.run(Run.kt:25)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:112)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:19)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:166)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:164)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:181)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:200)
	at io.titandata.titan.Cli.main(Cli.kt:56)
```

## Steps to Reproduce the Problem

Build an image locally and try to run it under titan.

## Version

Titan 0.3.0

**Comment by pioro** [comment]
Until bug is fixed a proposed workaround it to push a local image to a local repository.
List of steps:

```
 docker run -d -p 15000:5000 --restart=always --name registry registry:2
 docker tag database:18.4.0-xe localhost:15000/database
 docker login localhost:15000
 docker push localhost:15000/database
```
